// TradingView 분류(영문) → 한글 라벨.
//
// 분류 자체는 TradingView 것을 빌린다(우리가 종목을 고르지 않는다 = 편입 기준을 설명할 필요가 없다).
//   다만 라벨까지 영문이면 한국 섹터 카드와 같은 화면에서 눈이 두 번 바뀐다 — 이름만 우리말로 바꾼다.
//   ⚠️ key(영문)는 그대로 둔다. 캐시·정렬·비교가 전부 영문 키 기준이라 라벨만 갈아끼우는 구조여야
//     TradingView 가 분류를 늘려도(모르는 이름) 화면이 안 깨진다 — 사전에 없으면 영문을 그대로 쓴다.
//
// 용어는 앱의 한국 섹터 카드와 맞췄다(반도체·방산·정유·리츠·외식 …). 직역보다 그쪽을 우선한다.

const SECTOR_KR: Record<string, string> = {
  "Commercial Services": "기업서비스",
  "Communications": "통신",
  "Consumer Durables": "내구소비재",
  "Consumer Non-Durables": "비내구소비재",
  "Consumer Services": "소비자서비스",
  "Distribution Services": "유통서비스",
  "Electronic Technology": "전자기술",
  "Energy Minerals": "에너지자원",
  "Finance": "금융",
  "Health Services": "의료서비스",
  "Health Technology": "의료기술",
  "Industrial Services": "산업서비스",
  "Miscellaneous": "기타",
  "Non-Energy Minerals": "비에너지자원",
  "Process Industries": "소재·공정산업",
  "Producer Manufacturing": "산업재 제조",
  "Retail Trade": "소매유통",
  "Technology Services": "IT서비스",
  "Transportation": "운송",
  "Utilities": "유틸리티",
};

const INDUSTRY_KR: Record<string, string> = {
  "Advertising/Marketing Services": "광고·마케팅",
  "Aerospace & Defense": "항공우주·방산",
  "Agricultural Commodities/Milling": "농산물·제분",
  "Air Freight/Couriers": "항공화물·특송",
  "Airlines": "항공사",
  "Alternative Power Generation": "신재생발전",
  "Aluminum": "알루미늄",
  "Apparel/Footwear": "의류·신발",
  "Apparel/Footwear Retail": "의류·신발 소매",
  "Auto Parts: OEM": "자동차부품(OEM)",
  "Automotive Aftermarket": "자동차 애프터마켓",
  "Beverages: Alcoholic": "주류",
  "Beverages: Non-Alcoholic": "음료(비주류)",
  "Biotechnology": "바이오",
  "Broadcasting": "방송",
  "Building Products": "건축자재",
  "Cable/Satellite TV": "케이블·위성방송",
  "Casinos/Gaming": "카지노·게임",
  "Chemicals: Agricultural": "농약·비료",
  "Chemicals: Major Diversified": "종합화학",
  "Chemicals: Specialty": "정밀화학",
  "Coal": "석탄",
  "Computer Peripherals": "컴퓨터 주변기기",
  "Computer Processing Hardware": "컴퓨터·서버",
  "Construction Materials": "건설자재",
  "Consumer Sundries": "생활용품",
  "Containers/Packaging": "포장·용기",
  "Contract Drilling": "시추",
  "Data Processing Services": "데이터처리 서비스",
  "Department Stores": "백화점",
  "Discount Stores": "대형마트",
  "Drugstore Chains": "드럭스토어",
  "Electric Utilities": "전력",
  "Electrical Products": "전기장비",
  "Electronic Components": "전자부품",
  "Electronic Equipment/Instruments": "전자장비·계측",
  "Electronic Production Equipment": "전자·반도체 장비",
  "Electronics Distributors": "전자부품 유통",
  "Electronics/Appliance Stores": "가전 판매",
  "Electronics/Appliances": "가전",
  "Engineering & Construction": "엔지니어링·건설",
  "Environmental Services": "환경서비스",
  "Finance/Rental/Leasing": "금융·리스",
  "Financial Conglomerates": "종합금융",
  "Financial Publishing/Services": "금융정보 서비스",
  "Food Distributors": "식품유통",
  "Food Retail": "식품소매",
  "Food: Major Diversified": "종합식품",
  "Food: Meat/Fish/Dairy": "육류·수산·유제품",
  "Food: Specialty/Candy": "제과·특수식품",
  "Gas Distributors": "가스공급",
  "Home Furnishings": "가구·홈퍼니싱",
  "Home Improvement Chains": "홈인테리어 유통",
  "Homebuilding": "주택건설",
  "Hospital/Nursing Management": "병원·요양",
  "Hotels/Resorts/Cruise lines": "호텔·리조트·크루즈",
  "Household/Personal Care": "생활·퍼스널케어",
  "Industrial Conglomerates": "산업재 복합기업",
  "Industrial Machinery": "산업기계",
  "Industrial Specialties": "산업소재",
  "Information Technology Services": "IT 서비스",
  "Insurance Brokers/Services": "보험중개·서비스",
  "Integrated Oil": "종합석유",
  "Internet Retail": "인터넷 소매",
  "Internet Software/Services": "인터넷 SW·서비스",
  "Investment Banks/Brokers": "투자은행·증권",
  "Investment Managers": "자산운용",
  "Investment Trusts/Mutual Funds": "투자신탁·펀드",
  "Life/Health Insurance": "생명·건강보험",
  "Major Banks": "대형은행",
  "Major Telecommunications": "대형통신",
  "Managed Health Care": "건강보험 관리(HMO)",
  "Marine Shipping": "해운",
  "Medical Distributors": "의료 유통",
  "Medical Specialties": "의료기기·진단",
  "Medical/Nursing Services": "의료·요양 서비스",
  "Miscellaneous": "기타",
  "Miscellaneous Commercial Services": "기타 기업서비스",
  "Motor Vehicles": "완성차",
  "Movies/Entertainment": "영화·엔터",
  "Multi-Line Insurance": "종합보험",
  "Oil & Gas Pipelines": "원유·가스 파이프라인",
  "Oil & Gas Production": "원유·가스 생산",
  "Oil Refining/Marketing": "정유",
  "Oilfield Services/Equipment": "유전서비스·장비",
  "Other Consumer Services": "기타 소비자서비스",
  "Other Consumer Specialties": "기타 소비재",
  "Other Metals/Minerals": "기타 금속·광물",
  "Other Transportation": "기타 운송",
  "Packaged Software": "패키지 소프트웨어",
  "Pharmaceuticals: Generic": "제네릭 제약",
  "Pharmaceuticals: Major": "대형 제약",
  "Pharmaceuticals: Other": "기타 제약",
  "Precious Metals": "귀금속",
  "Property/Casualty Insurance": "손해보험",
  "Publishing: Newspapers": "신문·출판",
  "Pulp & Paper": "제지",
  "Railroads": "철도",
  "Real Estate Development": "부동산 개발",
  "Real Estate Investment Trusts": "리츠",
  "Recreational Products": "레저용품",
  "Regional Banks": "지역은행",
  "Restaurants": "외식",
  "Semiconductors": "반도체",
  "Services to the Health Industry": "의료산업 서비스",
  "Specialty Insurance": "특수보험",
  "Specialty Stores": "전문소매",
  "Specialty Telecommunications": "특수통신",
  "Steel": "철강",
  "Telecommunications Equipment": "통신장비",
  "Tobacco": "담배",
  "Tools & Hardware": "공구·하드웨어",
  "Trucking": "화물운송",
  "Trucks/Construction/Farm Machinery": "트럭·건설·농기계",
  "Water Utilities": "수도",
  "Wholesale Distributors": "도매유통",
  "Wireless Telecommunications": "무선통신",
};

/** 영문 분류명 → 한글. 사전에 없으면 영문 그대로(분류가 늘어도 화면이 안 깨진다). */
export function usSectorKrLabel(name: string): string {
  return SECTOR_KR[name] ?? INDUSTRY_KR[name] ?? name;
}

/** 사전에 있는 이름인가 — 팝업에서 영문 원명을 같이 보여줄지 판단용. */
export function hasUsKrLabel(name: string): boolean {
  return name in SECTOR_KR || name in INDUSTRY_KR;
}
